del *.dcu /q /s
del *.identcache /q /s
del *.local /q /s
del *.rsm /q /s
del *.vlb /q /s
del *.vrc /q /s
del *.stat /q /s
rd /q /s __history
rd /q /s __recovery
rd /q /s LauncherAPI\__history
rd /q /s LauncherAPI\__recovery
rd /q /s LauncherAPI\FilesValidation\__history
rd /q /s LauncherAPI\FilesValidation\__recovery
rd /q /s AuxUtils\__history
rd /q /s AuxUtils\__recovery
rd /q /s Avanguard\__history
